services:
   gs.client:
      class: Google_Client
      autowire: true
      calls:
        - [setAuthConfig, ['%env(GS_AUTH_FILE)%']]
        - [setScopes, [['https://www.googleapis.com/auth/spreadsheets']]]
   Google_Client: '@gs.client'
   Google_Service_Sheets:
      class: Google_Service_Sheets
      arguments:
        $clientOrConfig: '@gs.client'
   Google_Service_Drive:
      class: Google_Service_Drive
      arguments:
         $clientOrConfig: '@gs.client'


