parameters:
  spreadsheet_auth_url: !php/const App\Constants\AppConstants::SPREADSHEET_AUTH_URL
  drive_auth_url: !php/const App\Constants\AppConstants::DRIVE_AUTH_URL

services:
   gs.client:
      class: Google_Client
      autowire: true
      calls:
        - [setAuthConfig, ['%env(GS_AUTH_FILE)%']]
        - [setScopes, [['%spreadsheet_auth_url%' , '%drive_auth_url%']]]
   Google_Client: '@gs.client'
   Google_Service_Sheets:
      class: Google_Service_Sheets
      arguments:
        $clientOrConfig: '@gs.client'
   Google_Service_Drive:
      class: Google_Service_Drive
      arguments:
         $clientOrConfig: '@gs.client'